### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by ha6000** [rojo-rbx/rojo#360]
Stack trace
```
RUST_BACKTRACE=1 rojo build -o build.rbxm
thread 'main' panicked at 'not yet implemented', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rbx_binary-0.4.1/src/serializer.rs:160:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: std::panicking::begin_panic
  12: rbx_binary::serializer::generate_type_infos
  13: rbx_binary::serializer::encode
  14: librojo::commands::build::build
  15: rojo::start_build
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  18: rojo::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  23: std::panicking::try
             at src/libstd/panicking.rs:270
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is a bug in Rojo.
[ERROR rojo] 
[ERROR rojo] Please consider filing a bug: https://github.com/LPGhatguy/rojo/issues
[ERROR rojo] 
[ERROR rojo] Details: not yet implemented
```
If you think its something to do with my project, let me know and I will send the source files.
also if you want full stack trace, let me know.

**Comment by ha6000** [comment]
fixed if I add a x to the extension
